include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Import organization
    prefer_relative_imports: true
    always_use_package_imports: false

    # String formatting
    prefer_single_quotes: true

    # Code quality
    unnecessary_null_checks: true
    use_super_parameters: true
